/* Generated By:JJTree: Do not edit this line. ASTEqual.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEqual extends SimpleNode {
  public ASTEqual(int id) {
    super(id);
  }

  public ASTEqual(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5387523d82b5aa7597a0bb01d8bc487e (do not edit this line) */
