/* Generated By:JJTree: Do not edit this line. ASTGreaterThan.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGreaterThan extends SimpleNode {
  public ASTGreaterThan(int id) {
    super(id);
  }

  public ASTGreaterThan(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=643e6b8efe10f5c6a4ef6af8e47b1e63 (do not edit this line) */
