/* Generated By:JJTree: Do not edit this line. ASTGreaterThanEqual.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGreaterThanEqual extends SimpleNode {
  public ASTGreaterThanEqual(int id) {
    super(id);
  }

  public ASTGreaterThanEqual(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed02ef7dcedd042747ba34fa75f9def8 (do not edit this line) */
