/* Generated By:JJTree: Do not edit this line. ASTLessThanEqual.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLessThanEqual extends SimpleNode {
  public ASTLessThanEqual(int id) {
    super(id);
  }

  public ASTLessThanEqual(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d44d154d2d35a9ce1a65aebd8cb52423 (do not edit this line) */
