/* Generated By:JJTree: Do not edit this line. ASTMultiply.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMultiply extends SimpleNode {
  public ASTMultiply(int id) {
    super(id);
  }

  public ASTMultiply(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5f39976440cb7610c4f0bc8b7d83a4a2 (do not edit this line) */
