/* Generated By:JJTree: Do not edit this line. ASTSwitchFor.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSwitchFor extends SimpleNode {
  public ASTSwitchFor(int id) {
    super(id);
  }

  public ASTSwitchFor(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b63640b72a53a6100a13970cde61db2d (do not edit this line) */
