/* Generated By:JavaCC: Do not edit this line. CLParserDefaultVisitor.java Version 7.0.13 */
public class CLParserDefaultVisitor implements CLParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarDecl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssignment node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSwitchFor node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLoopIf node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOutString node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLessThanEqual node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGreaterThanEqual node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEqual node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNotEqual node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGreaterThan node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLessThan node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAdd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSubtract node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMultiply node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDivide node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFactor node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTConstant node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=8332a843742084ac5e0628995e6fa176 (do not edit this line) */
