/* Generated By:JavaCC: Do not edit this line. CLParserTreeConstants.java Version 7.0.13 */
public interface CLParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVARDECL = 1;
  public int JJTVOID = 2;
  public int JJTASSIGNMENT = 3;
  public int JJTSWITCHFOR = 4;
  public int JJTLOOPIF = 5;
  public int JJTOUTSTRING = 6;
  public int JJTLESSTHANEQUAL = 7;
  public int JJTGREATERTHANEQUAL = 8;
  public int JJTEQUAL = 9;
  public int JJTNOTEQUAL = 10;
  public int JJTGREATERTHAN = 11;
  public int JJTLESSTHAN = 12;
  public int JJTADD = 13;
  public int JJTSUBTRACT = 14;
  public int JJTMULTIPLY = 15;
  public int JJTDIVIDE = 16;
  public int JJTFACTOR = 17;
  public int JJTCONSTANT = 18;


  public String[] jjtNodeName = {
    "Program",
    "VarDecl",
    "void",
    "Assignment",
    "SwitchFor",
    "LoopIf",
    "OutString",
    "LessThanEqual",
    "GreaterThanEqual",
    "Equal",
    "NotEqual",
    "GreaterThan",
    "LessThan",
    "Add",
    "Subtract",
    "Multiply",
    "Divide",
    "Factor",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=7605430da203454bda558b33d2708728 (do not edit this line) */
