/* Generated By:JavaCC: Do not edit this line. CLParserVisitor.java Version 7.0.13 */
public interface CLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTSwitchFor node, Object data);
  public Object visit(ASTLoopIf node, Object data);
  public Object visit(ASTOutString node, Object data);
  public Object visit(ASTLessThanEqual node, Object data);
  public Object visit(ASTGreaterThanEqual node, Object data);
  public Object visit(ASTEqual node, Object data);
  public Object visit(ASTNotEqual node, Object data);
  public Object visit(ASTGreaterThan node, Object data);
  public Object visit(ASTLessThan node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSubtract node, Object data);
  public Object visit(ASTMultiply node, Object data);
  public Object visit(ASTDivide node, Object data);
  public Object visit(ASTFactor node, Object data);
  public Object visit(ASTConstant node, Object data);
}
/* JavaCC - OriginalChecksum=145371b1970bc8553856fa85ca83d924 (do not edit this line) */
