/* Generated By:JJTree&JavaCC: Do not edit this line. CLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int VARS = 7;
  /** RegularExpression Id. */
  int CODE = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int STR = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int CHAR = 12;
  /** RegularExpression Id. */
  int SWITCH = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int OTHER = 15;
  /** RegularExpression Id. */
  int ENDSWITCH = 16;
  /** RegularExpression Id. */
  int LOOPIF = 17;
  /** RegularExpression Id. */
  int HOLDS = 18;
  /** RegularExpression Id. */
  int ENDLOOP = 19;
  /** RegularExpression Id. */
  int OUT = 20;
  /** RegularExpression Id. */
  int EQ = 21;
  /** RegularExpression Id. */
  int NEQ = 22;
  /** RegularExpression Id. */
  int LE = 23;
  /** RegularExpression Id. */
  int GE = 24;
  /** RegularExpression Id. */
  int GT = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int ASSIGN = 27;
  /** RegularExpression Id. */
  int PLUS = 28;
  /** RegularExpression Id. */
  int MINUS = 29;
  /** RegularExpression Id. */
  int MUL = 30;
  /** RegularExpression Id. */
  int DIV = 31;
  /** RegularExpression Id. */
  int SEMI = 32;
  /** RegularExpression Id. */
  int COLON = 33;
  /** RegularExpression Id. */
  int LPAREN = 34;
  /** RegularExpression Id. */
  int RPAREN = 35;
  /** RegularExpression Id. */
  int IDENTIFIER = 36;
  /** RegularExpression Id. */
  int INTEGER = 37;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 38;
  /** RegularExpression Id. */
  int STRING_LITERAL = 39;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"startProgram\"",
    "\"endProgram\"",
    "\"variables:\"",
    "\"code:\"",
    "\"int\"",
    "\"string\"",
    "\"float\"",
    "\"char\"",
    "\"switchFor\"",
    "\"case\"",
    "\"other:\"",
    "\"endswitchFor\"",
    "\"loopif\"",
    "\"holds\"",
    "\"endloop\"",
    "\"outString\"",
    "\"==\"",
    "\"<>\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<FLOAT_LITERAL>",
    "<STRING_LITERAL>",
    "<CHAR_LITERAL>",
  };

}
